### ISSUE TITLE
Error in replicating your results

### ISSUE THREAD

**Issue by NicuSV** [TommasoBelluzzo/SystemicRisk#1] opened 2017-12-16 21:25 UTC
Hi, Tommaso,
Thank you for sharing your code. Unfortunately, when I run the code (file run.m), I get some errors. Matlab is not my usual software, I just wanna implement something. I've run the code with different versions of Matlab, including R2016b, R2014b and R2012a, and the error is the same.
At the beginning, I set the path to the folder where are the code files (SR folder): cd 'C:\Matlab\SR'; after that, I run the 'run' file and get the following errors:

Undefined function or variable 'detectImportOptions'.
Error in parse_dataset>parse_dataset_internal (line 73)
    opts = detectImportOptions(file,'Sheet',1);
Error in parse_dataset (line 19)
    data = parse_dataset_internal(res.file);
Error in run (line 12)
data = parse_dataset(fullfile(path,'\Datasets\Example.xlsx')); 

I have read that usually these errors are due to the different versions of Matlab, but unfortunately, I couldn't solve the problem in this way. Could you please take a look over these errors? And, also, what is the Matlab version in which you run your code?
Thank you very much.

Best,
Nicu

**Comment by TommasoBelluzzo** [comment] 2018-01-11 02:19
Hi Nicu. Your deduction was correct and the error was caused by an update I committed without checking for potential compatibility issues. Now it's fixed and everything is working properly under my Matlab 2014b environment. Thanks for reporting the issue and for your patience (I couldn't find enough time to undertake this task).

**Closed** 2018-01-11 02:20 UTC
