### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by wangyazhao001** [TommasoBelluzzo/SystemicRisk#4] opened 2020-02-01 04:34 UTC
When I run the run.m in the MATLAB2018B of Windows 10,there is an error:  

错误使用 parallel.FevalFuture/fetchNext (line 217)
The function evaluation completed with an error.

出错 run_spillover>run_spillover_internal (line 70)
            [future_index,value] = fetchNext(futures);

出错 run_spillover (line 37)
    result = run_spillover_internal(data,out_temp,out_file,ipr.bandwidth,ipr.lags,ipr.h,ipr.generalized,ipr.analyze);

出错 run (line 90)
result_spillover = run_spillover(data,out_temp_spillover,out_file_spillover,252,2,4,true,true);

原因:
    错误使用 statmvnrobj (line 23)
    Covariance matrix SIGMA is not positive-definite.
 
How to solve it?

**Comment by TommasoBelluzzo** [comment] 2020-02-01 15:52
I spotted the problem. This is due to the fact that Lehman Brothers time series become illiquid after the default and my current variance check is not enough to avoid zero covariance in the VARM model. Stay tuned for an update.

**Comment by TommasoBelluzzo** [comment] 2020-02-01 22:19
I uploaded the new version and the issue is fixed now.

**Closed by TommasoBelluzzo** 2020-02-01 22:19 UTC
